name = "counseling-messenger-bot"
main = "src/index.js"
compatibility_date = "2026-05-14"

[vars]
GEMINI_API_KEY = "AIzaSyACogd3YGWeldvAuKwttrbBrLB4gFi4Gi8"
VERIFY_TOKEN = "CareMeJesus2026"
PAGE_ACCESS_TOKEN = "EAANegy5XgKABRUyZBP9xEmJLwhZANzLWPCrOrHZCUEqUBJKaWssi1pVvhYayZAKrDQ26k2bF1KH626S74RZClAZBGMnupvUYiGDjOzzshb4FoBLZAHcaWfLnMYZBMxjHGT02RQJeSAUOdYrIRUe8RlVHdwDcujX6RuY1asXp7yzZAqfaG7ZBM3WsHPQGhG6ywBiSoLBAypedOCyq7JKiekJruu"
