name = "counseling-messenger-bot"
main = "src/index.js"
compatibility_date = "2026-05-14"

[vars]
GEMINI_API_KEY = "AIzaSyCBGhwcEp18NXSH9DH9-qu1tRssf0FxqJA,AIzaSyAREisL8-nTjyHsD9Um1IyS9X5Vs6Nq8_A,AIzaSyBOm8N_LWYCglnM7NRbdnYQ-kXnQ8cMsww,AIzaSyACogd3YGWeldvAuKwttrbBrLB4gFi4Gi8,AIzaSyAjFvidNZAOnpLnwmPSW1u6nIC0N9L6bnU"
VERIFY_TOKEN = "CareMeJesus2026"
PAGE_ACCESS_TOKEN = "EAANegy5XgKABRUyZBP9xEmJLwhZANzLWPCrOrHZCUEqUBJKaWssi1pVvhYayZAKrDQ26k2bF1KH626S74RZClAZBGMnupvUYiGDjOzzshb4FoBLZAHcaWfLnMYZBMxjHGT02RQJeSAUOdYrIRUe8RlVHdwDcujX6RuY1asXp7yzZAqfaG7ZBM3WsHPQGhG6ywBiSoLBAypedOCyq7JKiekJruu"
