name = "counseling-messenger-bot"
main = "src/index.js"
compatibility_date = "2026-05-14"

[vars]
GEMINI_API_KEY = "AIzaSyCBGhwcEp18NXSH9DH9-qu1tRssf0FxqJA"
VERIFY_TOKEN = "CareMeJesus2026"
PAGE_ACCESS_TOKEN = "PASTE_YOUR_FACEBOOK_PAGE_ACCESS_TOKEN_HERE"
